# Generated by Django 3.1 on 2020-08-06 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registerItem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='divicescategory',
            name='slug',
            field=models.SlugField(max_length=100, null=True, unique=True),
        ),
    ]
